# Generated by Django 5.2.6 on 2025-09-14 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plan', models.CharField(max_length=20, unique=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre no ingresado', max_length=20)),
                ('apellido', models.CharField(default='Apellido no ingresado', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dni', models.IntegerField(unique=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cuota_vencimiento', models.DateField(help_text='Fecha hasta la que está paga la cuota')),
                ('activo', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='GYM.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ClaseGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(max_length=80)),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('hora', models.TimeField()),
                ('cupo', models.PositiveIntegerField(default=30)),
                ('inscriptos', models.ManyToManyField(blank=True, related_name='clases', to='GYM.socio')),
            ],
        ),
    ]
