# Generated by Django 5.2.6 on 2025-09-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='socio',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
