# Generated by Django 5.2.6 on 2025-09-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0002_alter_plan_precio_mensual_alter_socio_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasegrupal',
            name='inscriptos',
        ),
    ]
