# Generated by Django 5.2.6 on 2025-09-21 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0003_remove_clasegrupal_inscriptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cuota_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
