# Generated by Django 5.2.6 on 2025-09-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0004_alter_socio_cuota_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasegrupal',
            options={'ordering': ['nombre_clase', 'dia_semana', 'hora']},
        ),
    ]
